# Generated by Django 4.2 on 2024-05-23 10:48

import django.core.validators
from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_employee_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="number",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(120),
                    projects.models.validate_even,
                ]
            ),
        ),
    ]
